---
name: Docs PR
on:
  pull_request_target:
    types: [opened, synchronize, closed, reopened]

jobs:
  docs-build:
    permissions:
      contents: read
    name: Documentation Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Poetry
      uses: snok/install-poetry@v1.3.1
      with:
        version: 1.1.14
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Set up Python
      id: python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
        cache: poetry

    - name: Install dependencies
      if: steps.python.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root

    - name: Install library
      run: poetry install --no-interaction

    - name: Sphinx Build
      working-directory: ./docs
      run: |
        poetry run make html

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: docs/_build/html/

  docs-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: [docs-build]
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          preview: true
          # https://github.com/actions/deploy-pages/blob/main/action.yml#L36
